stages:
  - unit_tests
  - infrastructure
  - integration

# 共同基底：Python 3.12 + uv
default:
  image: ghcr.io/astral-sh/uv:python3.12
  before_script:
    - python -V
    - uv --version
    - uv sync
    # （選用）裝 xdist 讓 pytest 在單一 job 內也能多核心跑
    - uv run python -m pip install pytest-xdist
  variables:
    FLASK_ENV: "development"
    UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONUNBUFFERED: "1"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/uv
    - .cache/pip
    - .venv/

# 把 unit 測試切兩份併發：application / domain
.unit_template: &unit_template
  stage: unit_tests
  script:
    # 跑指定資料夾；-n auto 讓單一 job 裡也用多核心
    - uv run pytest -q -n auto "$TEST_PATH"
  rules:
    # 先只在 dev 的 push 與所有 MR 跑
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

unit:
  parallel:
    matrix:
      - TEST_PATH: "tests/application"
      - TEST_PATH: "tests/domain"
  <<: *unit_template
